### ISSUE TITLE
Mini issues

### ISSUE THREAD

**Issue by htngr** [aformatik/codchi#9]

**Comment by sebsgr** [comment]
Windows:
Files that have been copied from host to dev-environment (via Explorer) always belong to root user

**Comment by sebsgr** [comment]
Windows:
Files cannot be moved/copied directly to programs like InteliJ

**Comment by htngr** [comment]
Windows (from #3)

- [ ] If the FileManager is called from a program, nothing currently happens. (e.g. IntelliJ)
For wsl Environments it would be a possibility to call explorer.exe to open Windows Exporer on the host system.

**Comment by htngr** [comment]
Windows (from #18):

**Probably because connection to X-Server fails when Windows changes the network**

- [ ] Sometimes IntelliJ UI crashes without any UI Message. The IntelliJ process is still active and cannot be killed with STRG+C.
The following stack trace also gives no information about the crash.


```
NOTE: Picked up JDK_JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on, -Dswing.aatext=true
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2023-07-18 06:13:46,938 [   1474]   WARN - #c.i.o.v.n.p.l.VfsLog - VFS Log version differs from the implementation version: log null vs implementation -43
2023-07-18 06:13:47,493 [   2029]   WARN - #c.i.o.a.i.ActionManagerImpl - keymap "VSCode" not found PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=/nix/store/z8b5hm7y60hspfc50dcd77m5vjyc755j-idea-ultimate-2023.1.2/idea-ultimate/plugins/terminal, version=231.9011.34, package=null, isBundled=true)
2023-07-18 06:13:48,088 [   2624]   WARN - #c.j.p.PluginClassPathRuntimeCustomizer - There was more than one class loaded in Projector Plugin classloader - this is likely a bug!
Info  | RdCoroutineScope          | 68:DefaultDispatcher-worker-50 | RdCoroutineHost overridden
2023-07-18 06:13:57,280 [  11816]   WARN - #c.i.o.a.Application - issue detected: vm.options.env.vars (ignored)
2023-07-18 06:13:57,821 [  12357]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-e95fd0b84d23-JavaScript-IU-231.9011.34
2023-07-18 06:13:58,133 [  12669]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `com.android.tools.idea.gradle.model.impl.IdeCompositeBuildMapImpl`
2023-07-18 06:13:58,133 [  12669]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `com.android.tools.idea.gradle.project.sync.IdeSyncExecutionReport`
2023-07-18 06:13:58,352 [  12888]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `org.jetbrains.kotlin.android.synthetic.idea.AndroidExtensionProperties`
2023-07-18 06:13:58,645 [  13181]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `org.jetbrains.plugins.gradle.model.data.AnnotationProcessingData$AnnotationProcessorOutput`
2023-07-18 06:13:58,727 [  13263]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `org.jetbrains.plugins.gradle.model.data.AnnotationProcessingData$AnnotationProcessorOutput`
2023-07-18 06:13:58,919 [  13455]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `org.jetbrains.kotlin.android.synthetic.idea.AndroidExtensionProperties`
2023-07-18 06:13:58,937 [  13473]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `org.jetbrains.kotlin.android.synthetic.idea.AndroidExtensionProperties`
2023-07-18 06:13:58,955 [  13491]   WARN - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Cannot find class `com.android.tools.idea.gradle.project.sync.idea.KotlinProperties`
2023-07-18 06:14:18,162 [  32698]   WARN - #c.i.e.r.RemoteProcessSupport - NOTE: Picked up JDK_JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on, -Dswing.aatext=true
2023-07-18 06:18:05,097 [ 259633]   WARN - #c.i.u.x.Binding - no accessors for org.jetbrains.idea.perforce.perforce.ConnectionId
2023-07-18 06:22:45,199 [ 539735]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'ClassSearchEverywhereContributor' did not finish search for 'Mu' in 3000ms. Maybe it should implement PossibleSlowContributor interface?2023-07-18 06:22:45,328 [ 539864]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'ClassSearchEverywhereContributor' did not finish search for 'Mu' in 3000ms. Maybe it should implement PossibleSlowContributor interface?2023-07-18 06:22:45,538 [ 540074]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'ClassSearchEverywhereContributor' did not finish search for 'Mult' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-07-18 06:22:45,729 [ 540265]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'ClassSearchEverywhereContributor' did not finish search for 'Multi' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-07-18 06:22:45,860 [ 540396]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'ClassSearchEverywhereContributor' did not finish search for 'Multi' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-07-18 06:24:46,017 [ 660553] SEVERE - #c.i.i.n.ide - Element class com.intellij.psi.impl.source.tree.java.MethodElement of type METHOD (class com.intellij.psi.impl.java.stubs.JavaStubElementTypes$4)
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.java.MethodElement of type METHOD (class com.intellij.psi.impl.java.stubs.JavaStubElementTypes$4)
        at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
        at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:98)
        at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
        at com.intellij.psi.util.PsiUtilCore.getVirtualFile(PsiUtilCore.java:354)
        at com.intellij.ide.navbar.impl.DefaultNavBarItemProvider.findParent(DefaultNavBarItemProvider.kt:44)
        at com.intellij.ide.navbar.impl.ImplKt.findParent(impl.kt:21)
        at com.intellij.ide.navbar.impl.ImplKt.access$findParent(impl.kt:1)
        at com.intellij.ide.navbar.impl.ImplKt$pathToItem$1.invoke(impl.kt:15)
        at com.intellij.ide.navbar.impl.ImplKt$pathToItem$1.invoke(impl.kt:14)
        at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
        at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at com.intellij.ide.navbar.impl.ImplKt.pathToItem(impl.kt:16)
        at com.intellij.ide.navbar.ide.NavBarServiceKt.contextModelInner(NavBarService.kt:154)
        at com.intellij.ide.navbar.ide.NavBarServiceKt.access$contextModelInner(NavBarService.kt:1)
        at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:136)
        at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:135)
        at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
        at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:92)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:91)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
        at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
        at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:126)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1$lambda$0(cancellableReadAction.kt:49)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1(cancellableReadAction.kt:47)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
        at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:91)
        at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:77)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:72)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
        at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
        at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
        at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:72)
        at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
        at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-18 06:24:46,025 [ 660561] SEVERE - #c.i.i.n.ide - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.34
2023-07-18 06:24:46,025 [ 660561] SEVERE - #c.i.i.n.ide - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-07-18 06:24:46,025 [ 660561] SEVERE - #c.i.i.n.ide - OS: Linux
2023-07-18 07:04:11,189 [3025725] SEVERE - #c.i.i.n.ide - Element class com.intellij.psi.impl.java.stubs.LambdaExpressionElementType$1 of type LAMBDA_EXPRESSION (class com.intellij.psi.impl.java.stubs.LambdaExpressionElementType)
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.java.stubs.LambdaExpressionElementType$1 of type LAMBDA_EXPRESSION (class com.intellij.psi.impl.java.stubs.LambdaExpressionElementType)
        at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
        at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:98)
        at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
        at com.intellij.psi.util.PsiUtilCore.getVirtualFile(PsiUtilCore.java:354)
        at com.intellij.ide.navbar.impl.DefaultNavBarItemProvider.findParent(DefaultNavBarItemProvider.kt:44)
        at com.intellij.ide.navbar.impl.ImplKt.findParent(impl.kt:21)
        at com.intellij.ide.navbar.impl.ImplKt.access$findParent(impl.kt:1)
        at com.intellij.ide.navbar.impl.ImplKt$pathToItem$1.invoke(impl.kt:15)
        at com.intellij.ide.navbar.impl.ImplKt$pathToItem$1.invoke(impl.kt:14)
        at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
        at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at com.intellij.ide.navbar.impl.ImplKt.pathToItem(impl.kt:16)
        at com.intellij.ide.navbar.ide.NavBarServiceKt.contextModelInner(NavBarService.kt:154)
        at com.intellij.ide.navbar.ide.NavBarServiceKt.access$contextModelInner(NavBarService.kt:1)
        at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:136)
        at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:135)
        at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
        at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:92)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:91)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
        at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
        at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:126)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1$lambda$0(cancellableReadAction.kt:49)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1(cancellableReadAction.kt:47)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
        at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
        at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:91)
        at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:77)
        at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:72)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
        at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
        at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
        at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
        at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:72)
        at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
        at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
        at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-18 07:04:11,193 [3025729] SEVERE - #c.i.i.n.ide - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.34
2023-07-18 07:04:11,194 [3025730] SEVERE - #c.i.i.n.ide - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-07-18 07:04:11,194 [3025730] SEVERE - #c.i.i.n.ide - OS: Linux
2023-07-18 07:30:26,801 [4601337] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Positive width should be defined for an inline element by [null]
com.intellij.diagnostic.PluginException: Positive width should be defined for an inline element by [null]
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
        at com.intellij.openapi.editor.impl.InlineInlayImpl.doUpdate(InlineInlayImpl.java:73)
        at com.intellij.openapi.editor.impl.InlayImpl.update(InlayImpl.java:59)
        at com.intellij.codeInsight.hints.declarative.impl.DeclarativeInlayHintsMouseMotionListener.mouseMoved(DeclarativeInlayHintsMouseMotionListener.kt:38)
        at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.lambda$mouseMoved$0(EditorEventMulticasterImpl.java:96)
        at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
        at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
        at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.mouseMoved(EditorEventMulticasterImpl.java:96)
        at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseMoved(EditorImpl.java:4462)
        at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6701)
        at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3403)
        at java.desktop/java.awt.Component.processEvent(Component.java:6425)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4588)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-07-18 07:30:26,803 [4601339] SEVERE - #c.i.o.e.i.ExtensionPointImpl - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.342023-07-18 07:30:26,803 [4601339] SEVERE - #c.i.o.e.i.ExtensionPointImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-07-18 07:30:26,803 [4601339] SEVERE - #c.i.o.e.i.ExtensionPointImpl - OS: Linux
2023-07-18 07:33:37,026 [4791562] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Positive width should be defined for an inline element by [null]
com.intellij.diagnostic.PluginException: Positive width should be defined for an inline element by [null]
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
        at com.intellij.openapi.editor.impl.InlineInlayImpl.doUpdate(InlineInlayImpl.java:73)
        at com.intellij.openapi.editor.impl.InlayImpl.update(InlayImpl.java:59)
        at com.intellij.codeInsight.hints.declarative.impl.DeclarativeInlayHintsMouseMotionListener.mouseMoved(DeclarativeInlayHintsMouseMotionListener.kt:38)
        at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.lambda$mouseMoved$0(EditorEventMulticasterImpl.java:96)
        at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
        at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
        at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.mouseMoved(EditorEventMulticasterImpl.java:96)
        at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseMoved(EditorImpl.java:4462)
        at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
        at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6701)
        at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3403)
        at java.desktop/java.awt.Component.processEvent(Component.java:6425)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4588)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-07-18 07:33:37,030 [4791566] SEVERE - #c.i.o.e.i.ExtensionPointImpl - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.342023-07-18 07:33:37,031 [4791567] SEVERE - #c.i.o.e.i.ExtensionPointImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-07-18 07:33:37,031 [4791567] SEVERE - #c.i.o.e.i.ExtensionPointImpl - OS: Linux
2023-07-18 07:38:45,591 [5100127]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2023-07-18 08:01:27,163 [6461699]   WARN - #o.j.i.maven - Maven pulling download listener stopped
2023-07-18 08:01:27,163 [6461699]   WARN - #o.j.i.maven - Maven pulling logger stopped
^C2023-07-18 08:08:03,754 [6858290]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 130
```
